name: Deploy to Azure App Service using ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Build the Docker image
      - name: Build the Docker image
        run: docker build -t spotlight:latest .

      # Log in to ACR
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{secrets.ACR_USERNAME}}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Tag the Docker image for ACR
      - name: Tag Docker image
        run: docker tag spotlight:latest ${{secrets.ACR_USERNAME}}.azurecr.io/spotlight:latest

      # Push the Docker image to ACR
      - name: Push Docker image to ACR
        run: docker push ${{secrets.ACR_USERNAME}}.azurecr.io/spotlight:latest

      # # Log in to Azure
      # - uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # # Deploy the Docker image to Azure App Service
      # - name: Deploy to Azure Web App
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: spotlight
      #     images: ${{secrets.ACR_USERNAME}}.azurecr.io/spotlight:latest
